CREATE DATABASE IF NOT EXISTS db;
USE db;
CREATE TABLE IF NOT EXISTS test(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);
ALTER TABLE test
    ADD IF NOT EXISTS task TEXT DEFAULT NULL,
    ADD IF NOT EXISTS description TEXT DEFAULT NULL;
